name: Build APKs

on:
  push:
    tags:
      - 'v*'  # Запуск на тегах вида v0.3, v1.0
  workflow_dispatch: # Запуск вручную

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PATH: ${{ runner.user }}/.local/bin:${{ env.PATH }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-distutils python3-pip git zip unzip \
            openjdk-8-jdk autoconf libtool pkg-config zlib1g-dev \
            libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip3 install --upgrade Cython==0.29.19 virtualenv

      - name: Install Buildozer
        run: |
          git clone https://github.com/kivy/buildozer.git
          cd buildozer
          python3 setup.py install
          cd ..

      - name: Build APKs (32-bit & 64-bit)
        run: |
          # Сборка 32-bit
          cp buildozer-32bit.spec buildozer.spec
          yes | buildozer android debug
          mv bin/*.apk bin/mobileapp001-32bit.apk

          # Очистка перед 64-bit сборкой
          rm -rf .buildozer
          rm -rf bin

          # Сборка 64-bit
          cp buildozer-64bit.spec buildozer.spec
          yes | buildozer android debug
          mv bin/*.apk bin/mobileapp001-64bit.apk

          # Список для проверки
          ls -l bin/
        shell: bash

      - name: Upload APKs to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
